### ISSUE TITLE
Show unsaved (no name) buffers

### ISSUE THREAD

**Issue by carlosedp** [weynhamz/vim-plugin-minibufexpl#1]
Is there any way to show the unsaved (no name) buffers in the bar? Too hard to implement?

Thanks

**Comment by weynhamz** [comment]
@carlosedp It has been implemented in my develop repo, you just need to set `g:miniBufExplBuffersNeeded` to 0 and `g:miniBufExplAutoStart` to 1.

**Comment by carlosedp** [comment]
Thanks!

Just one more thing. Would you merge this commit I made:
https://github.com/carlosedp/minibufexpl.vim/commit/79292f517d99fe71f785ba133782415101398d37

It prevents cycling thru windows if you are in MBE. I could not send a pull request.

Thanks.

**Comment by weynhamz** [comment]
@carlosedp that commit is not necessary any more, cyling buffers is disabled in any plugin window now, not just MBE.

**Comment by carlosedp** [comment]
Great! Thanks. I already switched to your dev branch on my VIM.

**Comment by weynhamz** [comment]
@carlosedp Great, a new version 6.5 will be released as soon as I finished all @fholgado's remaining issue.
