### ISSUE TITLE
Can not set custom tab colors

### ISSUE THREAD

**Issue by mikehaertl** [weynhamz/vim-plugin-minibufexpl#10]
I've tried to modify MBE's tab colors but it does not work. Here's what i have in my `.vimrc`:

``` vim
" minibufexplorer
let g:miniBufExplTabWrap = 1                " make tabs show complete (no broken on two lines)
let g:miniBufExplModSelTarget = 1           " try to always use right window for buffer
let g:did_minibufexplorer_syntax_inits = 1  " prevent override of color settings

" Set MBE colors (show all available groups with :hi)
hi link MBEVisibleNormal SpecialKey
hi link MBEVisibleActive Title
hi link MBEVisibleChanged StatusLine
hi link MBEVisibleActiveChanged Error
```

With the above settings, _all_ different tabs have the same standard color. If I remove the `g:did_minibufexplorer_syntax_inits = 1` it's using MBE's default highlighting, not mine.

If I output the current highlight groups with `:hi` it shows what I have configured above. But MBE ignores these settings.

**Comment by mikehaertl** [comment]
Ok, it works. But these group names are wrong in the help file:
- MBEVisibleActive
- MBEVisibleChangedActive

The correct names are:
- MBEVisibleActiveNormal
- MBEVisibleActiveChanged

The following configuration now works for me:

``` vim
hi link MBENormal Comment
hi link MBEChanged Special
hi link MBEVisibleNormal SpecialKey
hi link MBEVisibleChanged Title
hi link MBEVisibleActiveNormal StatusLine
hi link MBEVisibleActiveChanged Error
```

**Comment by weynhamz** [comment]
I changed the group names a while ago, I must have forgotten update the docs. 

Glad to see you figured it out, my attention was focused on aother project last a few days.

I will close this issue after I upate the docs.

Thanks.

**Comment by mikehaertl** [comment]
Great! BTW thanks again for your great job. :)
