### ISSUE TITLE
MBE can't be restored by vim -S Session.vim

### ISSUE THREAD

**Issue by jchain** [weynhamz/vim-plugin-minibufexpl#14]
How to reproduce:

I opened several files to edit, then I used :mks to save my session. But vim -S Session.vim shows an empty MBE. 

BTW: version 6.4.4 is working.

**Comment by weynhamz** [comment]
Should be fixed, please reopen if not.

**Comment by jchain** [comment]
Still no good. ':mks!' generates Session.vim but doesn't always save '-MiniBufExplorer-' on disk.

**Comment by weynhamz** [comment]
@jchain I might be related to you cnfigurations, what are your minibufexpl settings?

**Comment by jchain** [comment]
I have no customization, just the default setting. It is wired that 6.4.4 works but yours not. Is yours working?

**Comment by weynhamz** [comment]
@jchain Losts of things have changed since 6.4.4, you might need to read the doc first. And, by the way, default settings won't fire MBE up or will close MBE if the buffers opened is less than 2, that probably be the reason why '-MinibufExplorer-' won't save in the session.
