### ISSUE TITLE
Vim 7.4a Beta doesn't bring up MiniBufExpl

### ISSUE THREAD

**Issue by moll** [weynhamz/vim-plugin-minibufexpl#15]
Just gave the latest 7.4a Beta a try (from within [MacVim Snapshot 67](https://code.google.com/p/macvim/downloads/list)) and discovered MiniBufExpl doesn't show up any longer. Didn't have more time to debug, though.

**Comment by moll** [comment]
My bad. Seems I was too trigger happy here. Reopening the window I was testing around in seemed to have "fixed" this and MiniBufExpl does show up.

**Comment by weynhamz** [comment]
All right then, I was just about to try to install a newer Vim for testing, ^-^
