### ISSUE TITLE
bdelete buffer , delete all buffer and quit immediately

### ISSUE THREAD

**Issue by g1ra** [weynhamz/vim-plugin-minibufexpl#17]
Can't delete single buffer.
If multiple files is open 

:bdelete 
delete all buffer and cause vim quit.

:close 
is cause the following error

> Error detected while processing function > <SNR>77_QuitIfLastOpen:  
> line   12:  
> E173: 1 more file to edit

**Comment by weynhamz** [comment]
On 13-07-12, g1ra wrote:

> Can't delete single buffer.
> If multiple files is open 
> 
> :bdelete 
> delete all buffer and cause vim quit.
> 
> :close 
> is cause the following error
> 
> > Error detected while processing function > <SNR>77_QuitIfLastOpen:  
> > line   12:  
> > E173: 1 more file to edit               
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/techlivezheng/vim-plugin-minibufexpl/issues/17

Please update your Vim, proper handling of the quiting reqiures a newer
Vim.

**Comment by g1ra** [comment]
hg clone https://vim.googlecode.com/hg/ vim
hg update default
./configure --prefix=/usr/local --with-features=huge
vim --version
VIM - Vi IMproved 7.4a BETA (2013 Jul 6 ...

Thank you very much ! This is working basically.
