### ISSUE TITLE
Tab issues with miniBufExplBuffersNeeded = 1

### ISSUE THREAD

**Issue by saamalik** [weynhamz/vim-plugin-minibufexpl#19]
I would like the MiniBufExpl to always be open, so I set the following in my vimrc:
`let g:miniBufExplBuffersNeeded = 1`
1. Start vim
2. Open a file ![vim_open_file](https://f.cloud.github.com/assets/1455661/857192/b5201490-f54c-11e2-8900-ec0060668d20.png)
3. Open a new tab `:tabnew` ![vim_tabnew](https://f.cloud.github.com/assets/1455661/857196/bf79a50a-f54c-11e2-802f-4f87d09d004b.png)

First, the new tab MBE should not be showing buffers from the other tab (vimrc). However, the bigger problem is that you can't go back to the vimrc tab. Try clicking on the vimrc tab (or using `gt`). Both of these commands stop working.

**Comment by weynhamz** [comment]
@saamalik Are you sure this is a MBE problem, because it works fine here.

And about the "not show buffers from other tabs" request, it is just simply not possible, Vim does not work that way.

**Comment by weynhamz** [comment]
@saamalik You might need `:set mouse=a`.

**Comment by saamalik** [comment]
I'm not able to reproduce this bug with a minimal vimrc: https://gist.github.com/saamalik/f78adec2b19f50fe0f8b

Must be some plugin that I'm using--anyway, I stopped using:  let g:miniBufExplBuffersNeeded = 1
