### ISSUE TITLE
弱问buffer跳转时的颜色怎么配?

### ISSUE THREAD

**Issue by athom** [weynhamz/vim-plugin-minibufexpl#20]
非常感谢你把minibuffer改得这么好用,基本上非常易用且满足绝大多需求.

然而我个人使用的时候还有点小小的纠结
我现在跳转的时候[bufferX]只会高亮最左边的中括号,期待的情况是[bufferX]都被高亮

http://screencast.com/t/LUukQ4MJ

你示例的图看起来确实我期待的结果,不知道你是怎么设置的.
![](https://github-camo.global.ssl.fastly.net/386ce596da1602df1a7808dedfdb2bd73955887c/687474703a2f2f646c2e64726f70626f782e636f6d2f752f3131383635302f6d62652f73637265656e73686f74732f6d6265312e676966)

**Comment by weynhamz** [comment]
你只是在 Minibuffer 窗口中移动光标，是没有颜色区分的（ fholgado/minibufexpl.vim/issues/23 是关于这个特性的一个 Request，只是我个人不是很急需这个特性，一直没有去实现而已）。

图示的情况是在通过 `bn` 、`bp` 或者 `MBEbn` 、`MBEbp` 等命令改变 buffer。

**Comment by athom** [comment]
哈哈,原来如此.

图示看来是隐藏魔法的效果

单独一个光标在闪屏幕远了的情况不容易看见.

我看看能不能提个pull request

**Comment by 6thfdwp** [comment]
Hi thanks for your dedicated work. I tried to integrate it and had some problem with buffer highlighting and find this issue is the most relevant. I have no option but only put my question here. Hope someone will see and offer a help.
I follow the instruction to put these lines in my .vimrc file
hi link MBEVisibleChanged Title
hi link MBEVisibleActiveNormal StatusLine
hi link MBEVisibleActiveChanged Error

It does not work, all buffers are displayed as white, no difference when switching. I also tried in .vimrc
hi MBENormal               guifg=#808080 guibg=fg
hi MBEChanged              guifg=#CD5907 guibg=fg
hi MBEVisibleNormal        guifg=#5DC2D6 guibg=fg
hi MBEVisibleChanged       guifg=#F1266F guibg=fg
hi MBEVisibleActiveNormal  guifg=#A6DB29 guibg=fg
hi MBEVisibleActiveChanged guifg=#F1266F guibg=fg

still no effect. I cannot figure it out. Did I put in the wrong place or some other problems? Thanks in advance.

**Comment by athom** [comment]
hi,  you can try this option in you .vimrc

```
 hi MBESelecting            guifg=#BEEF13 guibg=fg
```

check your plugin source, make sure you have the changes like this

https://github.com/athom/vim-plugin-minibufexpl/commit/27b5f94c9432a2307ce9be781123af4611670e0d

let me know if it still blocks you.

**Comment by 6thfdwp** [comment]
Thanks. But still blocks me after making changes of what you told.

**Comment by 6thfdwp** [comment]
Maybe leave it for a while, sometimes answer shows up when you don't want it. Thanks anyway.

**Comment by athom** [comment]
hi @6thfdwp 

> It does not work, all buffers are displayed as white, no difference when switching. I also tried in .vimrc

according your description, maybe you just failed to load the plugin.

I can not help much due to the lacking of necessary info.

But you can try to debug in your local, with simple print info in some break points.

go the the plugin directory and edit the plugin/minibufexpl.vim file like this, hope it helps, good luck!

```
" Startup Check
"
" Has this plugin already been loaded? {{{
"
if exists('loaded_minibufexplorer')
  echo "ooops!!"
  finish
endif
let loaded_minibufexplorer = 1
echo "go on!"

" }}}

```

**Comment by 6thfdwp** [comment]
@athom 
It is strange that it did not echo anything after adding these. I am thinking if this plugin is not loaded properly, how is it possible to display buffer on the top and I can still use :bp :bn to switch between different buffers?

I can give you how my environment looks like. I just follow some guide to use pathogen to manage plugins. So minibuf is put in `~/.vim/bundle/minibufexpl`. And I put some mapping in the .vimrc

``` shell
nnoremap <D-u> :bp<cr>
inoremap <D-u> <esc>:bp<cr>
nnoremap <D-i> :bn<cr>
inoremap <D-i> <esc>:bn<cr>
nnoremap <D-y> :bw<cr>

let g:miniBufExplUseSingleClick = 1
let g:did_minibufexplorer_syntax_inits = 1
let g:miniBufExplAutoStart = 1
let g:miniBufExplDebugMode  = 1
" MiniBufExpl Colors
hi MBENormal               guifg=#808080 guibg=fg
hi MBESelecting            guifg=#BEEF13 guibg=fg
hi MBEChanged              guifg=#CD5907 guibg=fg
hi MBEVisibleNormal        guifg=#5DC2D6 guibg=fg
hi MBEVisibleChanged       guifg=#F1266F guibg=fg
hi MBEVisibleActiveNormal  guifg=#A6DB29 guibg=fg
```

**Comment by athom** [comment]
>  how is it possible to display buffer on the top and I can still use :bp :bn to switch between different buffers?

:bp :bn is one of default settings, you can `:h bp` to see the usage in the doc.

So I am 90% sure your problem is loading issue. 

Sorry I am not familiar with the pathogen, can you use other plugin via pathogen successfully? or just maybe this plugin not support pathogen?

BTW, I am using Vundle for plugin management, one of the possible issue of failed to loading is I forgot to set the Vundle trigger in my .vimrc. 

```
filetype off
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
source ~/.vim/VundleFile
filetype plugin indent on
```

**Comment by 6thfdwp** [comment]
Thanks for pointing out, but other plugins (nerdtree, commenter etc) work just fine. For pathogen, I know it is an alternative for vundle. I do not fully know every details about it, just follow their document guide to set up. And I had similar commands to set pathogen trigger at the beginning of my .vimrc. 

I will double check it and probably seek more help from you. Thanks!

**Comment by weynhamz** [comment]
You probably need to set 'g:did_minibufexplorer_syntax_inits = 1' so that MBE does not overwrite your settings, see '_MiniBufExplHighlighting_' section in the doc.

**Comment by 6thfdwp** [comment]
I have already set it. I also set the debugmode=1 and got some messages showed in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/2919741/2764606/7fe211f2-ca17-11e3-9104-d61cc352d671.png)

Still not sure whether the minibuf is loaded correctly.
