### ISSUE TITLE
Make :MBEbn and :MBEbp cycle over the last/first items

### ISSUE THREAD

**Issue by mikehaertl** [weynhamz/vim-plugin-minibufexpl#27]
Whe you use `:bn` on the last buffer in Vim, it will jump back to the first buffer. So you can use `:bn` endlessly and Vim will cycle through all buffers over and over.

This is not possible with `:MBEbn`: If you're on the most left buffer, it will do nothing. Is it possible to enable this with a feature flag?

**Comment by weynhamz** [comment]
Hey, checkout `g:miniBufExplCycleArround` option.

**Comment by mikehaertl** [comment]
Oops, i missed that (again). Thanks! :)
