### ISSUE TITLE
MiniBufExplorer loses color highlights when opening files via other plugins

### ISSUE THREAD

**Issue by carlosedp** [weynhamz/vim-plugin-minibufexpl#3]
When I try to open a file using some plugin, like NERDTree or ctrp-p, the MiniBufExplorer tab bar loses the highlights. If I use VIM ":e FILE" or the open icon, this doesn't happen.

The problem only happens on develop branch. Master is not affected.

**Comment by weynhamz** [comment]
I have encountered this problem several times, and commited a fix in 362f2d8, please fetch the newest develop branch and tell me if it still happens. Thanks.

**Comment by carlosedp** [comment]
Actually i'm running the latest develop branch and it still happens. Anything I can help?

**Comment by weynhamz** [comment]
How exactly you open the file? I am using NERDTree, and I have not encoutered this problem for a while. What is `ctrp-p`? I tried using command-t, it also works well. Any steps so I can reproduce the problem? Your `set rtp` output?

**Comment by carlosedp** [comment]
I see this problem using NERDTree. Ctrp-p is a plugin similar to Command-T but not ruby dependent. Just vim.

You can see my vimfiles in my repo: https://github.com/carlosedp/vimfiles

My RTP:

runtimepath=~/vimfiles,e:\Apps\vim/vimfiles,e:\Apps\vim\vimfiles\bundle\ack,e:\Apps\vim\vimfiles\bundle\Arduino-syntax,e:\Apps\vim\vimfiles\bundle\bclose,e:\Apps\vim\vimfiles\bundle\bufexplorer,e:\Apps\vim\vimfiles\bundle\color-solarized,e:\Apps\vim\vimfiles\bundle\color-tomorrow-night,e:\Apps\vim\vimfiles\bundle\ctrlp.vim,e:\Apps\vim\vimfiles\bundle\fountain,e:\Apps\vim\vimfiles\bundle\gundo,e:\Apps\vim\vimfiles\bundle\highlights,e:\Apps\vim\vimfiles\bundle\jekyll,e:\Apps\vim\vimfiles\bundle\minibufexplorer,e:\Apps\vim\vimfiles\bundle\mswin,e:\Apps\vim\vimfiles\bundle\nerdcommenter,e:\Apps\vim\vimfiles\bundle\nerdtree,e:\Apps\vim\vimfiles\bundle\python,e:\Apps\vim\vimfiles\bundle\snipmate-snippets,e:\Apps\vim\vimfiles\bundle\supertab,e:\Apps\vim\vimfiles\bundle\taglist-plus,e:\Apps\vim\vimfiles\bundle\tlib,e:\Apps\vim\vimfiles\bundle\vim-abolish,e:\Apps\vim\vimfiles\bundle\vim-addon-mw-utils,e:\Apps\vim\vimfiles\bundle\vim-autoclose,e:\Apps\vim\vimfiles\bundle\vim-coffee-script,e:\Apps\vim\vimfiles\bundle\vim-cucumber,

I isolated the modules and saw the the vim-autoclose plugin is causing the problem: https://github.com/Townk/vim-autoclose

**Comment by weynhamz** [comment]
Yes, plugin compatiblity could be tricky, I will look into it.

**Comment by carlosedp** [comment]
Thanks!

**Comment by weynhamz** [comment]
I am testing this issue, it indeed caused by vim-autoclose, I am useing `https://github.com/techlivezheng/vim-reset` to test the plugins, after the following setup and open NERDTree, MBE did lost its color highlightinng.

```
source vim-reset/activate
vim-reset --hard --confdir ~/.vim/.develop --add-rtp ~/.vim/bundle/plugin-autoclose/ --add-rtp ~/.vim/bundle/plugin-nerdtree --add-rtp ~/.vim/bundle/plugin-minibufexpl/
```

If I only use NERDTree and MBE by `vim-reset --hard --confdir ~/.vim/.develop --add-rtp ~/.vim/bundle/plugin-nerdtree --add-rtp ~/.vim/bundle/plugin-minibufexpl/`, it is working again.

I will keep you posted.

**Comment by weynhamz** [comment]
I have figured it out, it seems that 'AutoClose' calls `doautocmd FileType` everytime 'BufAdd', 'BufEnter' and 'BufNewFile' get triggered, in which it will reset the syntax for every buffer. There is currently no syntax defined for our MBE buffer's filetype 'minibufexpl'. so the previous syntax setting gets lost.

**Comment by weynhamz** [comment]
This issue should be fixed, feel free to reopen it if it still hurts.

The last issue before releasing version 6.5.0 has been conquered, version 6.5.0 will be rolling out in a few days.

**Comment by carlosedp** [comment]
Great! Thanks.
