### ISSUE TITLE
MBE does not highlight the active buffer

### ISSUE THREAD

**Issue by mikehaertl** [weynhamz/vim-plugin-minibufexpl#4]
I've opened 2 files in split windows. MBE highlights both of them with `MBEVisibleNormal`. It should use `MBEVisibleActive` for the active one.

This works fine in fholgado`s version.

I use `vim-gtk` (V7.3.429) on Ubuntu. Here's my customized vimrc.local: https://gist.github.com/1612035 (note the special Vundle setup which i use to share all plugins among all system users).

**Comment by weynhamz** [comment]
Your `set rtp` output might also be helpful, many problems cuased by plugin compatibility, sometimes even the order how the plugins are loaded.

**Comment by mikehaertl** [comment]
```
 runtimepath=/etc/vim/bundle/vundle,/etc/vim/bundle/xterm-color-table.vim,/etc/vim/bundle/vim-fugitive,/etc/vim/bundle/vim-p
lugin-minibufexpl,/etc/vim/bundle/pdv-standalone,/etc/vim/bundle/yii-api-vim,/etc/vim/bundle/matchit.zip,/etc/vim/bundle/Lust
yExplorer,/etc/vim/bundle/The-NERD-tree,/etc/vim/bundle/CSApprox,/etc/vim/bundle/Colour-Sampler-Pack,/etc/vim/bundle/vim-easy
motion,~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,/var/lib/vim/add
ons/after,~/.vim/after,/etc/vim/bundle/vundle/after,/etc/vim/bundle/xterm-color-table.vim/after,/etc/vim/bundle/vim-fugitive/
after,/etc/vim/bundle/vim-plugin-minibufexpl/after,/etc/vim/bundle/pdv-standalone/after,/etc/vim/bundle/yii-api-vim/after,/et
c/vim/bundle/matchit.zip/after,/etc/vim/bundle/LustyExplorer/after,/etc/vim/bundle/The-NERD-tree/after,/etc/vim/bundle/CSAppr
ox/after,/etc/vim/bundle/Colour-Sampler-Pack/after,/etc/vim/bundle/vim-easymotion/after,/etc/vim/bundle/yiiapi
```

**Comment by weynhamz** [comment]
Good, I will look into it before the end of this week.

**Comment by mikehaertl** [comment]
Thanks. And btw you really did a great job to fix some nasty issues in fholgados version. Much appreciated!

**Comment by greduan** [comment]
I also have this problem BTW. :)

Here's my `set rtp` result:

```
runtimepath=~/.vim/bundle/vundle
~/.vim/bundle/vim-colors-solarized
~/.vim/bundle/vim-numbertoggle
~/.vim/bundle/sudo-gui.vim
~/.vim/bundle/delimitMate
~/.vim/bundle/vitality.vim
~/.vim/bundle/vim-easymotion
~/.vim/bundle/vim-git-branch-info
~/.vim/bundle/vim-matchit
~/.vim/bundle/vim-fugitive
~/.vim/bundle/vim-repeat
~/.vim/bundle/vim-surround
~/.vim/bundle/vim-unimpaired
~/.vim/bundle/vim-css3-syntax
~/.vim/bundle/vim-less
~/.vim/bundle/python-syntax.vim
~/.vim/bundle/html5.vim
~/.vim/bundle/vim-javascript
~/.vim/bundle/vim-git
~/.vim/bundle/vim-markdown
~/.vim/bundle/tmux.vim
~/.vim/bundle/vim-markdown-folding
~/.vim/bundle/PIV
~/.vim/bundle/HTML-AutoCloseTag
~/.vim/bundle/base16-vim
~/.vim
/usr/local/Cellar/macvim/7.3-65/MacVim.app/Contents/Resources/vim/vimfiles
/usr/local/Cellar/macvim/7.3-65/MacVim.app/Contents/Resources/vim/runtime
/usr/local/Cellar/macvim/7.3-65/MacVim.app/Contents/Resources/vim/vimfiles/after
~/.vim/after
~/.vim/bundle/vundle/
~/.vim/bundle/vundle/after
~/.vim/bundle/vim-colors-solarized/after
```

**Comment by greduan** [comment]
To add to this, I've run across the problem it doesn't highlight anything. Just wanted to add that. :)

**Comment by mikehaertl** [comment]
@techlivezheng Forgive my impatience, but is there any news on this? I really like your version and think, it's almost perfect - except for the above problem. It would be sad to see this nice little project fall asleep just like fholgado's version :).

**Comment by neersighted** [comment]
I'm also experiencing this.

:bomb: Bump! :bomb:

**Comment by mikehaertl** [comment]
It seems like MBE is cursed: Every developer who tries to improve it also introduces new bugs. And after some time there's mysterious silence :D 

Maybe we can revert commit by commit and find out, when our problem started to appear? If only i had more time...

**Comment by mikehaertl** [comment]
Ok, i did some tests and found out, that the bug was introduced in commit dd2124d4. Everything works still fine in ff9fcfe. Now if only someone was brave enough to find out what's wrong there...

**Comment by weynhamz** [comment]
Very sorry for the delay, I am currently on the Chinese lunar new year
holiday at my parents' place where accessing the Internet is not easy.

Thanks for your biseting, it help me find the problem and I will fix it as
soon as I get back to my work place. For now, a dirty fix is to change the
1417 line of my develop version to the following:

if(bufname(l:i) == l:CurBufNum)

**Comment by weynhamz** [comment]
Hey, just a quick notice that this issue should be fixed in the develop branch by commits 572346d 452265c fd6992a 43a019a.

 I am closing this issue, feel free to reopen it, if it still hurts.

**Comment by mikehaertl** [comment]
Thanks a lot. When will we see this change in master? I use vundle to manage this plugin and it doesn't allow to select branches.

**Comment by weynhamz** [comment]
@mikehaertl I pushed it to the master of my repo, as of @fholgado's master, it has to wait.

**Comment by mikehaertl** [comment]
@techlivezheng Your master would be great - i've configured `techlivezheng/vim-plugin-minibufexpl` anyway :)
