### ISSUE TITLE
MiniBufExplorer shows empty after MBEOpen on VimEnter (with AutoStart disabled)

### ISSUE THREAD

**Issue by minkyn** [weynhamz/vim-plugin-minibufexpl#5]
I'm using the latest version from "develop" branch. My settings for MiniBufExplorer are as follows:

```
let g:miniBufExplAutoStart = 0
let g:miniBufExplBuffersNeeded = 0
```

And then I defined an autocmd:

```
autocmd VimEnter * MBEOpen
```

Now when I open a file "foo.txt", the MBE buffer shows up but contains nothing. What's worse, if I make changes to "foo.txt", the MBE refreshes highlighting and shows itself as well as other unmodifiable buffers. For example, it shows

```
[1:foo.txt]*![2:-MiniBufExplorer-]*
```

_PS_: As a context, here is my reason to explicitly call MBEOpen on VimEnter rather than set the auto start option. Besides MiniBufExplorer I also use NERDTree and TagBar plugins, and want to set up the layout in a way that those two windows take up the full height. This can't be done without calling MBEOpen first. Therefore I need to customize the initialization process.

**Comment by minkyn** [comment]
One more thing is whenever I type `:MBEOpen` or make it autorun on `VimEnter` as said above, I can always hear two successive beeps, but `:messages` doesn't show anything. (For experiment I even deleted all other plugins except for `pathogen` and `minibufexpl`, but the beeps still exist.)

**Comment by weynhamz** [comment]
Please do not do this, starting MBE when Vim starts is very tricky, it involves many condition checking. If you want to make MBE open after NERDTree and Tagbar, please adjust your `rtp` setting to make MBE entry appear after the other one, this way, MBE will load after NERDTree and Tagbar starting and show at the top of the window. In Vundle this should be easy, but in pathogen, one trick might be working is to rename the MBE's plugin directory and prefix it with something to make it show after all the other plugins directory.

**Comment by weynhamz** [comment]
I am reconsidering this, it should be possible to use it in your way.

**Comment by weynhamz** [comment]
Should be fixed in develop, closing this issue, fell free to reopen it if it still hurts.

**Comment by minkyn** [comment]
Thanks!
