### ISSUE TITLE
TabWrap option is broken

### ISSUE THREAD

**Issue by minkyn** [weynhamz/vim-plugin-minibufexpl#6]
I'm using the latest version from "develop" branch. My settings for MiniBufExplorer are as follows:

```
let g:miniBufExplTabWrap = 1
```

with all other options in default value.

When I open the second buffer, I receive the following warning message:

> Error detected while processing function <SNR>20_BufEnterHandler..<SNR>20_AutoUpdate..<SNR>20_StartExplorer..<SNR>20_DisplayBuffers..<SNR>20_ResizeWindow:
> line   36:
> E21: Cannot make changes, 'modifiable' is off

After hitting Enter, the MBE buffer is still able to show two buffers' names separated by a space, but any following action that triggers MBE's AutoUpdate() will cause those warning messages again.

**Comment by weynhamz** [comment]
Fixed in develop branch.
