### ISSUE TITLE
relativenumber not supported by Vim < 7.3

### ISSUE THREAD

**Issue by swardman** [weynhamz/vim-plugin-minibufexpl#7]
`relativenumber` is not supported by Vim before 7.3 (I have 7.2.445 here).

```
Error detected while processing function <SNR>15_AutoUpdate..<SNR>15_StartExplorer:
line   39:
E518: Unknown option: norelativenumber
```

Writing `silent! setlocal norelativenumber` instead of `setlocal norelativenumber` suppresses the error.

**Comment by weynhamz** [comment]
Fixed in develop branch.
